Pb-721 show share whiteboard link and add save whiteboard as pdf feature
nordeck/whiteboard pull request #16
Opened 2021-02-18 15:47 UTC by nurjinjafar

@skolmer  aaaand... i guess my IDE reformated the same files your IDE formated. i don't see any changes locally to not push them. so here you go.

2021-02-18 17:57 UTC, skolmer commented
> 
> 
> @skolmer aaaand... i guess my IDE reformated the same files your IDE formated. i don't see any changes locally to not push them. so here you go.
> could you please check if i overwrote any of your changes?!

IDE fight 😁 I will check tomorrow

2021-02-19 12:58 UTC, skolmer requested changes

2021-02-19 12:58 UTC, skolmer commented on src/js/main.js
> +                    var w = window.open("about:blank"); //Firefox will not allow downloads without extra window
Do you have some kind of adblocker or popup blocker installed? I tried this example in my firefox which hast uBlock extension installed and it is working: https://jsfiddle.net/ourcodeworld/rce6nn3z/2/

2021-02-19 13:39 UTC, nurjinjafar commented on src/js/main.js
> +                    var w = window.open("about:blank"); //Firefox will not allow downloads without extra window
without opening an new window the download won't work even in chrome (in widget context)

2021-02-19 14:48 UTC, skolmer commented
does "show share whiteboard link" in the title mean that the user is able again to share the url of the whiteboard? this was disabled because user should stay in the widget for now. The element team is even working on removing the popout button of the widget container.

2021-02-19 15:04 UTC, nurjinjafar commented
> does "show share whiteboard link" in the title mean that the user is able again to share the url of the whiteboard? this was disabled because user should stay in the widget for now. The element team is even working on removing the popout button of the widget container.

no only admin will be able to share the whiteboard link. for the user it is still removed. if oyu think it's wanted to be prevented then i can hide it again

2021-02-19 15:11 UTC, skolmer commented
> 
> 
> > does "show share whiteboard link" in the title mean that the user is able again to share the url of the whiteboard? this was disabled because user should stay in the widget for now. The element team is even working on removing the popout button of the widget container.
> 
> no only admin will be able to share the whiteboard link. for the user it is still removed. if you think it's wanted to be prevented then i can hide it again

ok, lets keep it then.

I did a small change to calculate how much the image should be scaled to always fit the available height and width of the pdf

2021-02-19 15:13 UTC, skolmer approved these changes

2021-02-19 15:13 UTC, merged